export const TJENESTER_PER_KATEGORI: Record<string, string[]> = {
  snekker: [
    'Gulv og parkett',
    'Kjøkkenmontering',
    'Baderomsrenovering',
    'Garderobe og innredning',
    'Dører og vinduer',
    'Terrasse og balkong',
    'Riving og demontering',
    'Trapper og rekkverk',
    'Panel og listverk',
    'Taktekking tre',
    'Loftinnredning',
    'Undertak og bjelkelag',
    'Garasjebygg tre',
    'Carport og bod',
    'Uteplassbygging',
    'Vindusbytte',
    'Dørbytte',
    'Sokkelbord og fasadekledning',
    'Pipe og ildsted ombygging',
    'Snekkerarbeid generelt',
  ],

  maler: [
    'Innvendig maling',
    'Utvendig maling',
    'Tapetsering',
    'Beising og lakkering',
    'Fasademaling',
    'Betongmaling',
    'Sparkling og overflatebehandling',
    'Sprøytemaling',
    'Gulvbelegg og laminat',
    'Flislegging',
    'Maling etter vannkadse',
    'Garasje og kjellermaling',
    'Maling av møbler og skap',
    'Tak og himlingsmaling',
    'Kalkpuss og spesialpuss',
    'Maling av gjerder og stakitt',
    'Vindusmaling',
    'Markering og trafikkmaling',
    'Epoksybelegg',
    'Malerarbeid generelt',
  ],

  elektriker: [
    'El-anlegg nybygg',
    'Ombygging el-anlegg',
    'Sikringsskap og fordeling',
    'Stikkontakter og brytere',
    'Innvendig belysning',
    'Utebelysning',
    'El-varme og varmekabler',
    'Ladepunkt elbil',
    'Solcelleinstallasjon',
    'Varmepumpe el-tilkobling',
    'Alarm og adgangskontroll',
    'Smarthjem og automasjon',
    'Nettverkskabler og data',
    'TV og antenne',
    'Jordfeilbryter',
    'Ly lynavleder',
    'Aggregat og nødstrøm',
    'Industri el-installasjon',
    'Lys i bad og våtrom',
    'Elektrikerarbeid generelt',
  ],

  rorlegger: [
    'Baderom renovering',
    'Varmtvannbereder bytte',
    'Rørlegger kjøkken',
    'Gulvvarme vannbåren',
    'Utvendig vann og avløp',
    'Frostsikring rør',
    'Toalett og servant',
    'Dusj og badekar',
    'Servant og blandebatteri',
    'Vaskemaskin tilkobling',
    'Oppvaskmaskin tilkobling',
    'Varmepumpe VVS',
    'Radiator og varmeanlegg',
    'Sprinkleranlegg',
    'Pumpe og trykkregulering',
    'Avløpssanering',
    'Rørfornying',
    'Lekkasjesøk',
    'Brannslukningsanlegg',
    'Rørleggerarbeid generelt',
  ],

  entreprenor: [
    'Totalrenovering',
    'Tilbygg og påbygg',
    'Garasje og carport',
    'Grunnarbeid og sprengning',
    'Riving og sanering',
    'Prosjektledelse',
    'Betong og muring',
    'Graving og masseflytting',
    'Drenering',
    'Støttemurer',
    'Tomtearbeid',
    'Veiarbeid og parkering',
    'Støyskjerm og gjerde',
    'Peling og fundamentering',
    'Isolering kjeller og grunn',
    'Miljøsanering',
    'Asfaltarbeid',
    'Brøyting og strøing',
    'Hagearbeid og anlegg',
    'Entreprenørarbeid generelt',
  ],
}

export const ALLE_TJENESTER_FLAT: string[] =
  Object.values(TJENESTER_PER_KATEGORI).flat()

export function tjenesterForKategori(
  kategori: string | null | undefined
): string[] {
  if (!kategori) return ALLE_TJENESTER_FLAT
  return TJENESTER_PER_KATEGORI[kategori] ?? ALLE_TJENESTER_FLAT
}
